name: "Label Actions"

on:
  issues:
    types: [labeled, unlabeled]
  pull_request:
    types: [labeled, unlabeled]

jobs:
  label-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/label-actions@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-path: .github/label-actions.yml
